### ISSUE TITLE
Issue with using both hub and node roles in the same server

### ISSUE THREAD

**Issue by williamtsoi1** [jhoblitt/puppet-selenium#45] opened 2015-05-27 07:19 UTC
Hi,

Using a simple manifest file (https://github.com/williamtsoi1/selenium-puppet/blob/master/manifests/default.pp), and I have the following error:

Error: Duplicate declaration: File[init-script] is already declared in file /home/ubuntu/selenium-puppet/modules/selenium/manifests/config.pp:40; cannot redeclare at /home/ubuntu/selenium-puppet/modules/selenium/manifests/config.pp:40 on node ip-10-70-0-193.ap-southeast-2.compute.internal

Is there some sort of conflict between the selenium::hub and selenium::node classes?

**Comment by jhoblitt** [comment] 2015-05-27 16:35
It looks like this was caused by the PR that added debian support #42 .  That should have been caught by the acceptance tests as well.  It will be an easy fix.

**Comment by jhoblitt** [comment] 2015-07-27 16:30
Resolved by #46

**Closed by jhoblitt** 2015-07-27 16:30 UTC
